[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "F8NjHsqvBW3jCisV265DY69v1EyDYN4dKUof4FJsHZyU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/yasseen/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
